version: '3'

services:

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  app:
    tty: true
    environment: &app-environment
      DATABASE_URL: postgres://admin:admin@db/tcomments
      TELEGRAM_TOKEN: 1234815723:AAHAkpRGROOYOjzZXONvgK990mROjISOkbM
      TELEGRAM_BOT_USERNAME: "@dev_tcomments_bot"
      DOMAIN: 69e96a83cd09.ngrok.io
      SESSION_COOKIE_DOMAIN: 127.0.0.1
      SECRET_KEY: 9qD7OKjYzZ0d8EsjBIKQ4RR57A1GHZODT
      FLASK_APP: app:app
      FLASK_DEBUG: "1"
      FLASK_ENV: development

    build: .
    image: tcomments-web
    ports: ["5000:5000"]
    volumes: ['.:/work']
    depends_on: [db]
    entrypoint: flask
    command: run --host 0.0.0.0

  db:
    image: postgres
    ports: ["5432:5432"]
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tcomments
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
