version: '3'

services:

  app:
    tty: true
    environment: &app-environment
      DATABASE_URL: postgres://admin:admin@db/bot
      FLASK_APP: app:app
      FLASK_DEBUG: "1"
      FLASK_ENV: development

    build: .
    image: tcomments-web
    ports: ["5000:5000"]
    volumes: ['.:/work']
    depends_on: [db]
    entrypoint: flask
    command: run --host 0.0.0.0

  db:
    image: postgres
    ports: ["5432:5432"]
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tcomments
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
