version: '3'

services:

  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on: [app, web]
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificates:/certificates
    ports: ['443:443', '80:80']

  web:
    tty: true
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports: ['3000:3000']
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8080
    depends_on: ["app"]
    entrypoint: npm
    command: run dev

  app:
    tty: true
    environment: &app-environment
      DATABASE_URL: postgres://admin:admin@db/tcomments
      TELEGRAM_TOKEN: 1234815723:AAHAkpRGROOYOjzZXONvgK990mROjISOkbM
      TELEGRAM_BOT_USERNAME: "@dev_tcomments_bot"
      TELEGRAM_WEBHOOK_DOMAIN: localhost.dev
      SECRET_KEY: 9qD7OKjYzZ0d8EsjBIKQ4RR57A1GHZODT
      FLASK_APP: app:app
      FLASK_DEBUG: "1"
      FLASK_ENV: development

    build: .
    image: tcomments-web
    ports: ["4000:5000"]
    volumes: ['.:/work']
    depends_on: [db]
    entrypoint: flask
    command: run --host 0.0.0.0

  db:
    image: postgres
    ports: ["5432:5432"]
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tcomments
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
